src/main/java/it/strazz/primefaces/model/Car.java
package it.strazz.primefaces.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.collections.Predicate;

public class Car implements Serializable{

	private static final long serialVersionUID = 1L;

	private static List<Car> cars = new ArrayList<Car>();

	private Integer id;
	private String brand;
	private String color;
	private Integer year;
	private String notes;
	private boolean used;
	
	static{
		cars.add(new Car(0, "Honda","Yellow",1995,false,"Broken Brakes"));
		cars.add(new Car(1, "Volvo","Black",1973,true));
		cars.add(new Car(1, "Audi","Silver",1987,false));
		cars.add(new Car(1, "Renault","White",1963,true));
		cars.add(new Car(1, "Volkswagen","Black",1985,true));
	}	

	public Car(Integer id, String brand, String color, Integer year, boolean used,String notes) {
		super();
		this.id = id;
		this.brand = brand;
		this.color = color;
		this.year = year;
		this.used = used;
		this.notes = notes;
	}
	
	public Car(Integer id, String brand, String color, Integer year, boolean used) {
		this(id,brand,color,year,used,"");
	}
	
	public Car() {}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public boolean isUsed() {
		return used;
	}

	public void setUsed(boolean used) {
		this.used = used;
	}

	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public static List<Car> getAll(){
		return cars;

	}

	public static Car get(final Integer id){
		return (Car) CollectionUtils.find(cars, new Predicate() {
			public boolean evaluate(Object object) {
				return ((Car) object).getId().equals(id);
			}
		});
	}

	public static Car store(Car p){
		if(p.getId() == null){
			Car maxUserId = Collections.max(cars, new Comparator<Car>() {
				public int compare(Car o1, Car o2) {
					return o1.getId().compareTo(o2.getId());
				}
			});
			
			p.setId(maxUserId.getId()+1);
			
			cars.add(p);
		}else{
			cars.set(p.getId(), p);
		}

		return p;
	}

	public static void delete(Car p){
		cars.remove(p);
	}
}

src/main/java/it/strazz/primefaces/model/PermisoDTO.java
package it.strazz.primefaces.model;

import java.io.Serializable;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.collections.Predicate;

public class PermisoDTO {
    public static final String TIPO_NUEVO="N";
    public static final String TIPO_MODIFICACION="M";
    public static final String TIPO_ELIMINACION="E";
    private String clave;
    private String nombre;
    private List<RecursoSeguroDTO> permisos;

    private UsuarioDTO usuario;
    private Instant tsModificacion;
    private String tipo;


    public PermisoDTO(String clave, String nombre) {
        this.clave = clave;
        this.nombre = nombre;
    }

	public String getClave() {
		return clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<RecursoSeguroDTO> getPermisos() {
		return permisos;
	}

	public void setPermisos(List<RecursoSeguroDTO> permisos) {
		this.permisos = permisos;
	}

	public UsuarioDTO getUsuario() {
		return usuario;
	}

	public void setUsuario(UsuarioDTO usuario) {
		this.usuario = usuario;
	}

	public Instant getTsModificacion() {
		return tsModificacion;
	}

	public void setTsModificacion(Instant tsModificacion) {
		this.tsModificacion = tsModificacion;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public static String getTipoNuevo() {
		return TIPO_NUEVO;
	}

	public static String getTipoModificacion() {
		return TIPO_MODIFICACION;
	}

	public static String getTipoEliminacion() {
		return TIPO_ELIMINACION;
	}

    
}

src/main/java/it/strazz/primefaces/model/PrivilegioDTO.java
package it.strazz.primefaces.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.collections.Predicate;

public class PrivilegioDTO {
    public static final String PRIV_AUTO="PRIV_AUTO";
    public static final String PRIV_EDICION="PRIV_EDICION";
    public static final String PRIV_SEGURIDAD="PRIV_SEGURIDAD";
    private String clave;
    private String descripcion;
    public PrivilegioDTO(String privilegio, String descripcion) 
    {
        this.clave = privilegio;
        this.descripcion = descripcion;
    }
    public PrivilegioDTO() 
    {
    }
	public String getClave() {
		return clave;
	}
	public void setClave(String clave) {
		this.clave = clave;
	}
	public String getDescripcion() {
		return descripcion;
	}
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	public static String getPrivAuto() {
		return PRIV_AUTO;
	}
	public static String getPrivEdicion() {
		return PRIV_EDICION;
	}
	public static String getPrivSeguridad() {
		return PRIV_SEGURIDAD;
	}
    
}

src/main/java/it/strazz/primefaces/model/RecursoSeguroDTO.java
package it.strazz.primefaces.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.collections.Predicate;

public class RecursoSeguroDTO {
    private String recurso;
    private String descripcion;
    private RecursoSeguroDTO recursoPadre;


    public RecursoSeguroDTO(String recurso, String descripcion, RecursoSeguroDTO recursoPadre) {
        this.recurso = recurso;
        this.descripcion = descripcion;
        this.recursoPadre = recursoPadre;
    }

    @Override
    public String toString() {
        return "RecursoSeguroDTO{" +
                "recurso='" + recurso + '\'' +
                '}';
    }

	public String getRecurso() {
		return recurso;
	}

	public void setRecurso(String recurso) {
		this.recurso = recurso;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public RecursoSeguroDTO getRecursoPadre() {
		return recursoPadre;
	}

	public void setRecursoPadre(RecursoSeguroDTO recursoPadre) {
		this.recursoPadre = recursoPadre;
	}
    
}

src/main/java/it/strazz/primefaces/model/RolDTO.java
package it.strazz.primefaces.model;

import java.io.Serializable;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.collections.Predicate;

public class RolDTO {
    public static final String TIPO_NUEVO="N";
    public static final String TIPO_MODIFICACION="M";
    public static final String TIPO_ELIMINACION="E";
    private String clave;
    private String nombre;

    private List<RecursoSeguroDTO> permisos;

    private UsuarioDTO usuario;
    private Instant tsModificacion;
    private String tipo;


    public RolDTO(String clave, String nombre) {
        this.clave = clave;
        this.nombre = nombre;
    }

	public String getClave() {
		return clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<RecursoSeguroDTO> getPermisos() {
		return permisos;
	}

	public void setPermisos(List<RecursoSeguroDTO> permisos) {
		this.permisos = permisos;
	}

	public UsuarioDTO getUsuario() {
		return usuario;
	}

	public void setUsuario(UsuarioDTO usuario) {
		this.usuario = usuario;
	}

	public Instant getTsModificacion() {
		return tsModificacion;
	}

	public void setTsModificacion(Instant tsModificacion) {
		this.tsModificacion = tsModificacion;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public static String getTipoNuevo() {
		return TIPO_NUEVO;
	}

	public static String getTipoModificacion() {
		return TIPO_MODIFICACION;
	}

	public static String getTipoEliminacion() {
		return TIPO_ELIMINACION;
	}

    
}

src/main/java/it/strazz/primefaces/AdvancedDetailExampleBean.java
package it.strazz.primefaces;

import it.strazz.primefaces.detail.DynaPropertyModel;
import it.strazz.primefaces.detail.FormControlBuilder;
import it.strazz.primefaces.detail.ReflectionDynaFormModelBuilder;

import java.beans.PropertyDescriptor;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.primefaces.extensions.model.dynaform.DynaFormControl;
import org.primefaces.extensions.model.dynaform.DynaFormLabel;
import org.primefaces.extensions.model.dynaform.DynaFormRow;

@ManagedBean
@ViewScoped
public class AdvancedDetailExampleBean extends BasicDetailExampleBean{
	
	private static final String NOTES_FIELD = "notes";
	private static final long serialVersionUID = 1L;
	
	@Override
	protected Comparator<PropertyDescriptor> getPropertyComparator() {
		return new Comparator<PropertyDescriptor>() {
			public int compare(PropertyDescriptor first, PropertyDescriptor second) {
				if(NOTES_FIELD.equals(first.getName())){
					return 1;
				}else if(NOTES_FIELD.equals(second.getName())){
					return -1;
				}else{
					return ReflectionDynaFormModelBuilder.DEFAULT_PROPERTY_COMPARATOR.compare(first, second);
				}
			}
		};
	}
	
	@Override
	protected Map<String, FormControlBuilder> getCustomBuilders() {
		Map<String, FormControlBuilder> toReturn = new HashMap<String, FormControlBuilder>(0);
		toReturn.put(NOTES_FIELD, new FormControlBuilder() {
			public void populateRow(DynaFormRow row) {
				//We will show notes in a textArea
				DynaFormLabel label = row.addLabel(NOTES_FIELD);
		        DynaFormControl input = row.addControl(new DynaPropertyModel(NOTES_FIELD), "text");  
		        label.setForControl(input);
			}
		});
		return toReturn;
	}
}

src/main/java/it/strazz/primefaces/BasicDetailExampleBean.java
package it.strazz.primefaces;

import it.strazz.primefaces.detail.FormControlBuilder;
import it.strazz.primefaces.detail.ReflectionDynaFormModelBuilder;

import java.beans.PropertyDescriptor;
import java.io.Serializable;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.apache.commons.beanutils.MethodUtils;
import org.primefaces.extensions.model.dynaform.DynaFormModel;

@ManagedBean
@ViewScoped
public class BasicDetailExampleBean implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	private Object model;
	private Class currentClass;
	private String currentClassName;
	private Integer id;
	private Boolean disabled = false;
	private DynaFormModel formModel;
	
	public final void onPreRender(){
		try {
			currentClass = Class.forName(currentClassName);
			this.formModel = new ReflectionDynaFormModelBuilder(currentClass)
				.setExcludedProperties("id")
				.setPropertySortComparator(getPropertyComparator())
				.putCustomBuilders(getCustomBuilders())
				.build();
			if(id != null){
				this.model = MethodUtils.invokeExactStaticMethod(currentClass, "get", new Object[]{id});
			}else{
				this.model = currentClass.newInstance();
			}
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}
	
	protected Comparator<PropertyDescriptor> getPropertyComparator() {
		return ReflectionDynaFormModelBuilder.DEFAULT_PROPERTY_COMPARATOR;
	}

	protected Map<String, FormControlBuilder> getCustomBuilders() {
		//No Custom
		return new HashMap<String, FormControlBuilder>(0);
	}

	public final String save(){
		try {
			MethodUtils.invokeExactStaticMethod(currentClass, "store", new Object[]{this.model});
			return "param.xhtml?class=" + currentClassName + "&faces-redirect=true";
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}
	
	public String getCurrentClassName() {
		return currentClassName;
	}

	public void setCurrentClassName(String currentClass) {
		this.currentClassName = currentClass;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Boolean getDisabled() {
		return disabled;
	}

	public void setDisabled(Boolean disabled) {
		this.disabled = disabled;
	}

	public Object getModel() {
		return model;
	}

	public DynaFormModel getFormModel() {
		return formModel;
	}
}

src/main/java/it/strazz/primefaces/BasicExampleBean.java
package it.strazz.primefaces;

import it.strazz.primefaces.columns.ColumnModel;
import it.strazz.primefaces.columns.ReflectionColumnModelBuilder;
import it.strazz.primefaces.model.User;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean
@ViewScoped
public class BasicExampleBean implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	private List<ColumnModel> columns = new ArrayList<ColumnModel>(0);
	
	@PostConstruct
	public void init() {
		columns = new ReflectionColumnModelBuilder(User.class).
					setExcludedProperties("id").
					build();
	}
	
	public List<User> getUsers(){
		return User.getAll();
	}

	public List<ColumnModel> getColumns() {
		return columns;
	}
}

src/main/java/it/strazz/primefaces/DynamicExampleBean.java
package it.strazz.primefaces;

import it.strazz.primefaces.columns.ColumnModel;
import it.strazz.primefaces.columns.ReflectionColumnModelBuilder;
import it.strazz.primefaces.model.User;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.apache.commons.beanutils.MethodUtils;

@ManagedBean
@ViewScoped
public class DynamicExampleBean implements Serializable{
	
	private List<ColumnModel> columns = new ArrayList<ColumnModel>(0);
	private String currentClass = User.class.getName();
	
	@PostConstruct
	public void init() {
		onChangeClass();
	}
	
	public void onChangeClass(){
		try {
			columns = new ReflectionColumnModelBuilder(Class.forName(currentClass)).
					setExcludedProperties("id").
					build();
		} catch (ClassNotFoundException e) {
			//Will not happen
			columns = null;
		}
	}
	
	public List<Object> getData(){
		try {
			return (List<Object>) MethodUtils.invokeExactStaticMethod(Class.forName(currentClass), "getAll", null);
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	public List<ColumnModel> getColumns() {
		return columns;
	}
	public String getCurrentClass() {
		return currentClass;
	}

	public void setCurrentClass(String currentClass) {
		this.currentClass = currentClass;
	}
}

src/main/java/it/strazz/primefaces/ViewParamExampleBean.java
package it.strazz.primefaces;

import it.strazz.primefaces.columns.ColumnModel;
import it.strazz.primefaces.columns.ReflectionColumnModelBuilder;
import it.strazz.primefaces.model.User;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.apache.commons.beanutils.MethodUtils;

@ManagedBean
@ViewScoped
public class ViewParamExampleBean implements Serializable{
	
	private List<ColumnModel> columns = new ArrayList<ColumnModel>(0);
	private String currentClass = User.class.getName();
	
	public void onPreRender() {
		try {
			columns = new ReflectionColumnModelBuilder(Class.forName(currentClass)).
					setExcludedProperties("id").
					build();
		} catch (ClassNotFoundException e) {
			//Will not happen
			columns = null;
		}
	}
	
	public List<Object> getData(){
		try {
			return (List<Object>) MethodUtils.invokeExactStaticMethod(Class.forName(currentClass), "getAll", null);
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	public List<ColumnModel> getColumns() {
		return columns;
	}
	
	public String getCurrentClass() {
		return currentClass;
	}

	public void setCurrentClass(String currentClass) {
		this.currentClass = currentClass;
	}
}

src/main/webapp/advancedDetail.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions">
<h:head>
</h:head>
<f:metadata>
	<f:viewParam name="class" value="#{advancedDetailExampleBean.currentClassName}"></f:viewParam>
	<f:viewParam name="id" value="#{advancedDetailExampleBean.id}" converter="javax.faces.Integer"></f:viewParam>
	<f:viewParam name="disabled" value="#{advancedDetailExampleBean.disabled}" converter="javax.faces.Boolean"></f:viewParam>
	<f:event listener="#{advancedDetailExampleBean.onPreRender}" type="preRenderView"></f:event>
</f:metadata>
<h:body>
	<h:form>
		<p:messages id="messages" showSummary="true"/>
		
	    <pe:dynaForm id="dynaForm" value="#{advancedDetailExampleBean.formModel}" var="data">
	        <pe:dynaFormControl type="string" for="txt">
	        	<p:inputText 
	        		id="txt" 
	        		value="#{advancedDetailExampleBean.model[data.name]}"
	        		disabled="#{advancedDetailExampleBean.disabled}"/>
	        </pe:dynaFormControl>
	        <pe:dynaFormControl type="boolean" for="boolean">
	           	<p:selectBooleanCheckbox 
	           		id="boolean" 
	           		value="#{advancedDetailExampleBean.model[data.name]}"
	           		disabled="#{advancedDetailExampleBean.disabled}"/>
	        </pe:dynaFormControl>
	        <pe:dynaFormControl type="integer" for="integer">
	           	<p:inputText 
	           		id="integer" 
	           		value="#{advancedDetailExampleBean.model[data.name]}" 
	           		converter="javax.faces.Integer"
	           		disabled="#{advancedDetailExampleBean.disabled}"/>
	        </pe:dynaFormControl>
	        <pe:dynaFormControl type="text" for="text">
	           	<p:inputTextarea
	           		id="text" 
	           		value="#{advancedDetailExampleBean.model[data.name]}" 
	           		disabled="#{advancedDetailExampleBean.disabled}"/>
	        </pe:dynaFormControl>
	    </pe:dynaForm>
    </h:form>
</h:body>
</html>

src/main/webapp/basic.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>
<h:body>
	<p:dataTable var="user" value="#{basicExampleBean.users}">
		<p:columns 
			value="#{basicExampleBean.columns}" 
			var="column"
			headerText="#{column.header}">
			<h:outputText value="#{user[column.property]}" />
		</p:columns>
	</p:dataTable>
</h:body>
</html>

src/main/webapp/basicDetail.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions">
<h:head>
</h:head>
<f:metadata>
	<f:viewParam name="class" value="#{basicDetailExampleBean.currentClassName}"></f:viewParam>
	<f:viewParam name="id" value="#{basicDetailExampleBean.id}" converter="javax.faces.Integer"></f:viewParam>
	<f:viewParam name="disabled" value="#{basicDetailExampleBean.disabled}" converter="javax.faces.Boolean"></f:viewParam>
	<f:event listener="#{basicDetailExampleBean.onPreRender}" type="preRenderView"></f:event>
</f:metadata>
<h:body>
	<h:form>
		<p:messages id="messages" showSummary="true"/>
		
	    <pe:dynaForm id="dynaForm" value="#{basicDetailExampleBean.formModel}" var="data">
	        <pe:dynaFormControl type="string" for="txt">
	        	<p:inputText 
	        		id="txt" 
	        		value="#{basicDetailExampleBean.model[data.name]}"
	        		disabled="#{basicDetailExampleBean.disabled}"/>
	        </pe:dynaFormControl>
	        <pe:dynaFormControl type="boolean" for="boolean">
	           	<p:selectBooleanCheckbox 
	           		id="boolean" 
	           		value="#{basicDetailExampleBean.model[data.name]}"
	           		disabled="#{basicDetailExampleBean.disabled}"/>
	        </pe:dynaFormControl>
	        <pe:dynaFormControl type="integer" for="integer">
	           	<p:inputText 
	           		id="integer" 
	           		value="#{basicDetailExampleBean.model[data.name]}" 
	           		converter="javax.faces.Integer"
	           		disabled="#{basicDetailExampleBean.disabled}"/>
	        </pe:dynaFormControl>
	        <pe:dynaFormControl type="text" for="text">
	           	<p:inputTextarea
	           		id="text" 
	           		value="#{basicDetailExampleBean.model[data.name]}" 
	           		disabled="#{basicDetailExampleBean.disabled}"/>
	        </pe:dynaFormControl>
	    </pe:dynaForm>
	    
	    <p:commandButton
	    	process="@form"
	    	value="Save" 
	    	disabled="#{basicDetailExampleBean.disabled}"
	    	action="#{basicDetailExampleBean.save}"/>
    </h:form>
</h:body>
</html>

src/main/webapp/dynamic.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>
<h:body>
	<h:form>
		<h:panelGrid columns="2" style="margin-bottom:10px" cellpadding="5">
	        <p:outputLabel for="currentClass" value="Class:" />
	        <p:selectOneRadio id="currentClass" value="#{dynamicExampleBean.currentClass}">
	            <f:selectItem itemLabel="User" itemValue="it.strazz.primefaces.model.User" />
	            <f:selectItem itemLabel="Car" itemValue="it.strazz.primefaces.model.Car" />
	            <p:ajax listener="#{dynamicExampleBean.onChangeClass}" update="@form"/>
	        </p:selectOneRadio>
	    </h:panelGrid>
		<p:dataTable var="obj" value="#{dynamicExampleBean.data}">
			<p:columns 
				value="#{dynamicExampleBean.columns}" 
				var="column"
				headerText="#{column.header}">
				<p:selectBooleanCheckbox 
					value="#{obj[column.property]}" 
					disabled="true"
					rendered="#{column.type.toString() == 'boolean'}"/>
				<h:outputText value="#{obj[column.property]}" rendered="#{column.type.toString() != 'boolean'}" />
			</p:columns>
		</p:dataTable>
	</h:form>
</h:body>
</html>

src/main/webapp/param.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>
<f:metadata>
	<f:viewParam name="class" value="#{viewParamExampleBean.currentClass}"></f:viewParam>
	<f:event listener="#{viewParamExampleBean.onPreRender}" type="preRenderView"></f:event>
</f:metadata>
<h:body>
	<h:outputLink 
		value="basicDetail.xhtml?faces-redirect=true">
			Create
			<f:param name="class" value="#{viewParamExampleBean.currentClass}"/>
	</h:outputLink>
	<p:dataTable var="obj" value="#{viewParamExampleBean.data}">
		<p:column>
			<h:outputLink 
				value="basicDetail.xhtml?faces-redirect=true">
					Edit
					<f:param name="id" value="#{obj.id}"/>
					<f:param name="class" value="#{viewParamExampleBean.currentClass}"/>
			</h:outputLink>
		</p:column>
		<p:column>
			<h:outputLink 
				value="basicDetail.xhtml?faces-redirect=true">
					View
					<f:param name="id" value="#{obj.id}"/>
					<f:param name="disabled" value="true"/>
					<f:param name="class" value="#{viewParamExampleBean.currentClass}"/>
			</h:outputLink>
		</p:column>
		<p:columns 
			value="#{viewParamExampleBean.columns}" 
			var="column"
			headerText="#{column.header}">
			<p:selectBooleanCheckbox 
				value="#{obj[column.property]}" 
				disabled="true"
				rendered="#{column.type.toString() == 'boolean'}"/>
			<h:outputText value="#{obj[column.property]}" rendered="#{column.type.toString() != 'boolean'}" />
		</p:columns>
	</p:dataTable>
</h:body>
</html>